<![CDATA[
#!/usr/bin/env groovy
// Source: https://gist.github.com/merikan/228cdb1893fca91f0663bab7b095757c (Public Gist - Educational Use)
// Test case: Simple scripted pipeline for Jenkins server inspection
node {
  DOCKER_PATH = sh (script: 'command -v docker', returnStdout: true).trim()
  echo "Docker path: ${DOCKER_PATH}"
  
  FREE_MEM = sh (script: 'free -m', returnStdout: true).trim()
  echo "Free memory: ${FREE_MEM}"
  
  echo sh(script: 'env|sort', returnStdout: true)
}
    ]]>